version: '3.8'
services:
  mongors1n1:
    container_name: mongors1n1
    image: mongo
    deploy:
      restart_policy:
        condition: any      
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    ports:
      - 27017:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/mongo_shard/data1:/data/db

  mongors1n2:
    container_name: mongors1n2
    image: mongo
    deploy:
      restart_policy:
        condition: any      
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    ports:
      - 27027:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/mongo_shard/data2:/data/db
  mongors1n3:
    container_name: mongors1n3
    image: mongo
    deploy:
      restart_policy:
        condition: any      
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    ports:
      - 27037:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/mongo_shard/data3:/data/db
  mongors2n1:
    container_name: mongors2n1
    image: mongo
    deploy:
      restart_policy:
        condition: any      
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    ports:
      - 27047:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/mongo_shard/data4:/data/db
  mongors2n2:
    container_name: mongors2n2
    image: mongo
    deploy:
      restart_policy:
        condition: any      
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    ports:
      - 27057:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/mongo_shard/data5:/data/db
  mongors2n3:
    container_name: mongors2n3
    image: mongo
    deploy:
      restart_policy:
        condition: any      
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    ports:
      - 27067:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/mongo_shard/data6:/data/db
  mongocfg1:
    container_name: mongocfg1
    image: mongo
    deploy:
      restart_policy:
        condition: any      
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/mongo_shard/config1:/data/db
  mongocfg2:
    container_name: mongocfg2
    image: mongo
    deploy:
      restart_policy:
        condition: any      
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/mongo_shard/config2:/data/db
  mongocfg3:
    container_name: mongocfg3
    image: mongo
    deploy:
      restart_policy:
        condition: any      
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/mongo_shard/config3:/data/db


  mongos1:
    container_name: mongos1
    image: mongo
    deploy:
      restart_policy:
        condition: any      
    depends_on:
      - mongocfg1
      - mongocfg2
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017 --bind_ip_all 
    ports:
      - 27019:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  mongos2:
    container_name: mongos2
    image: mongo
    deploy:
      restart_policy:
        condition: any      
    depends_on:
      - mongocfg1
      - mongocfg2
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017 --bind_ip_all
    ports:
      - 27020:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  mongoshell:
    container_name: mongoshell
    image: mongo
    deploy:
      restart_policy:
        condition: any
    depends_on:
      - mongos1
      - mongos2
    command: bash -c "while true; do sleep 1; done"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - MONGO_SHARD_KEY
      - mongo_secret_key

secrets:
   MONGO_SHARD_KEY:
      external: true
   mongo_secret_key:
     file: ./secret.key 
